### ISSUE TITLE
作者大大能在GF里创建这个脚本吗

### ISSUE THREAD

**Issue by dodying** [hustlzp/jquery-s2t#2]
我写了一个脚本，想调用它，希望作者大大能将这个脚本上传到[GreaseFork](https://greasyfork.org/)

**Comment by dodying** [comment]
我将这个脚本上传到了GreaseFork，地址：https://greasyfork.org/zh-CN/scripts/21539
如果，作者大大感到冒犯，请联系我，我马上把它删除

**Comment by hustlzp** [comment]
没事的。

发自我的 iPhone

**Comment by dodying** [comment]
发现脚本无法作用到没有引用jQuery的网站，就修改了一下，只剩下转换文本的功能
地址：https://greasyfork.org/zh-CN/scripts/21541

**Comment by hustlzp** [comment]
好的👌🏻

发自我的 iPhone

**Comment by dodying** [comment]
再次感谢作者大大

**Comment by hustlzp** [comment]
哈哈，不客气

发自我的 iPhone
