### ISSUE TITLE
报个问题：呼的转换有错

### ISSUE THREAD

**Issue by shuguangbo** [hustlzp/jquery-s2t#3]
呼的简繁应该是一样的，在别的在线繁简转换器上试了一下。http://www.fantizi5.com/
但在jquery-s2t使用中，简体显示时呼转为唿，繁体显示时为呼。
从github下载的测试文件中加了呼字，按繁简转换按钮即可重现这个问题。

**Comment by shuguangbo** [comment]
又发现一个 猛 -- 勐

**Comment by hustlzp** [comment]
好的，我空了处理一下。
